name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Firmware
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: ZMK Build Action
        uses: zmkfirmware/zmk-build-action@v1
        with:
          board: nice_nano_v2
          shield: custom_75
          config_path: firmware/config
